/**
 * Write NMWC dispatch sample order files (generated by prisma/nmwc-dispatch-data.ts).
 *
 *   pnpm fixtures:dispatch -- --date=2026-09-25 [--out=tests/fixtures/nmwc]
 *
 * Files (same --date => byte-identical output):
 *   orders-20.csv      20 known stops, clean; fast tests
 *   orders-150.xlsx    150 stops incl. 3 unknown customers + 1 unknown item code (= seed --orders)
 *   orders-large.csv   ~400 stops for the benchmark; needs the 480-branch master (seed --customers=480)
 *   late-p1.csv        one late P1 order (extra "Priority" column = P1); customer from pickLateP1Customer:
 *                      a P1 branch not in orders-150 if there is one, else a hypermarket already in it
 *
 * --date defaults to tomorrow in Asia/Muscat. --out is relative to apps/web.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { tomorrowIso } from '../lib/dispatch/time';
import {
  ORDER_FILE_PRESETS,
  buildCustomers,
  generateLateOrderRows,
  generateOrderRows,
  pickLateP1Customer,
  rowsToCsv,
  rowsToXlsxBuffer,
  summarizeOrderRows,
  type OrderRow,
} from './nmwc-dispatch-data';

const WEB_ROOT = path.resolve(__dirname, '..');

function parseArgs(argv: string[]): { date: string; out: string } {
  let date = tomorrowIso();
  let out = path.join(WEB_ROOT, 'tests', 'fixtures', 'nmwc');
  for (const a of argv) {
    let m = /^--date=(.+)$/.exec(a);
    if (m) {
      if (!/^\d{4}-\d{2}-\d{2}$/.test(m[1]) || Number.isNaN(Date.parse(`${m[1]}T00:00:00Z`))) throw new Error(`--date expects YYYY-MM-DD (got "${m[1]}")`);
      date = m[1];
      continue;
    }
    m = /^--out=(.+)$/.exec(a);
    if (m) {
      out = path.resolve(WEB_ROOT, m[1]);
      continue;
    }
    if (a === '--') continue;
    throw new Error(`Unknown option "${a}". Use --date=YYYY-MM-DD and --out=<dir>.`);
  }
  return { date, out };
}

function report(file: string, rows: OrderRow[]) {
  const s = summarizeOrderRows(rows);
  console.log(`  ${path.basename(file).padEnd(18)} ${String(s.rows).padStart(4)} rows  ${String(s.stops).padStart(3)} stops  ${String(s.salesOrders).padStart(3)} SOs  ${String(s.cases).padStart(6)} cases`);
}

function main() {
  const { date, out } = parseArgs(process.argv.slice(2));
  fs.mkdirSync(out, { recursive: true });
  console.log(`Writing NMWC dispatch fixtures for delivery date ${date} to ${out}`);

  const small = generateOrderRows({ date, ...ORDER_FILE_PRESETS.small });
  const smallFile = path.join(out, 'orders-20.csv');
  fs.writeFileSync(smallFile, rowsToCsv(small));
  report(smallFile, small);

  const demo = generateOrderRows({ date, ...ORDER_FILE_PRESETS.demo });
  const demoFile = path.join(out, 'orders-150.xlsx');
  fs.writeFileSync(demoFile, rowsToXlsxBuffer(demo));
  report(demoFile, demo);

  const large = generateOrderRows({ date, ...ORDER_FILE_PRESETS.large });
  const largeFile = path.join(out, 'orders-large.csv');
  fs.writeFileSync(largeFile, rowsToCsv(large));
  report(largeFile, large);

  const lateCustomer = pickLateP1Customer(demo, buildCustomers());
  const late = generateLateOrderRows(date, lateCustomer.code, { branch: lateCustomer.branchCode });
  const lateFile = path.join(out, 'late-p1.csv');
  fs.writeFileSync(lateFile, rowsToCsv(late));
  report(lateFile, late);
  console.log(`  late order: ${lateCustomer.code}${lateCustomer.branchCode ? ` / ${lateCustomer.branchCode}` : ''} ${lateCustomer.name}`);
}

main();
