-- AlterTable
ALTER TABLE "RunJob" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "startedAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "finishedAt" SET DATA TYPE TIMESTAMPTZ(3);
